### ISSUE TITLE
Two objects with radio buttons on one page not working correctly

### ISSUE THREAD

**Issue by jveldhoen** [balexbyrd/sense-FieldUI#1]
Hi Alex,

When using two or more objects of this extension on one page as radio buttons, it only shows a colored dot for selected values for one object. See attached screenshot for clarification. I noticed that the dot is shown for a very short time when refreshing the page and then disappears.

![screenshot](https://cloud.githubusercontent.com/assets/3206677/17998985/67e2325e-6b77-11e6-8859-aa7c4121f960.png)

Do you have any idea how to resolve this?

Jeroen

**Comment by balexbyrd** [comment]
Hey Jeroen,

Thanks for bringing this up. I see exactly what you're talking about in my demo. A short term workaround would be to use a checkbox and 'Always one selected value' with no field written in the input box.

If you feel comfortable enough, you could also go into the senseFieldUI.js file and update the checkbox class to include 'checkbox-circle' on line 417. Clear your cache and refresh the page. This will turn the square checkbox into a circle.

`html += '<div class="checkbox checkbox-circle checkbox-'+btnColor+' checkbox-'+vars.ListType+' '+dis+'"><input class="styled"`

I know of a relatively quick solution which I'll build in shortly. I'll push a newer file up when completed and then close this out so you'll know it's done. 

Thanks again.

**Comment by balexbyrd** [comment]
Fixed! Please download a fresh copy and give it a spin.

**Comment by jveldhoen** [comment]
Great stuff Alex, works like a charm!
