### ISSUE TITLE
Word wrap alignment issue when 'Span Width?' enabled

### ISSUE THREAD

**Issue by dggauthier** [balexbyrd/sense-FieldUI#13]
I currently am trying to use the FieldUI extension to allow user to apply one of three selections. Two of the buttons are two-word options, which the third is a single word. When displaying, the third item does not render vertically the same as the other two. 

![image](https://user-images.githubusercontent.com/19920595/29474073-2124eec2-8428-11e7-94e0-227aeac5f4b0.png)

**Comment by balexbyrd** [comment]
Thanks for bringing attention to this. Please pull the most recent code, try again, and update this issue if it's been fixed.

Thanks again!

**Comment by dggauthier** [comment]
Bug has been fixed. Thank you very much for the quick turn around.
