### ISSUE TITLE
Incorrect import of qlik

### ISSUE THREAD

**Issue by ardfar68** [balexbyrd/sense-FieldUI#18]
This extension imports the qlik module as js/qlik which is unsupported and will fail to render in June 2018 of Qlik Sense.

See: https://help.qlik.com/en-US/sense-developer/April2018/Subsystems/Extensions/Content/Howtos/call-qlik-library.htm

![image](https://user-images.githubusercontent.com/37073132/40538143-20045fe4-6011-11e8-9874-eee68c77dab0.png)

**Comment by balexbyrd** [comment]
@ardfar68 Thanks for the heads up and the solution! I wasn't able to download the June 2018 version to test but I'll make the update.

Take care
