### ISSUE TITLE
Need to show Field Name when dimension value not selected

### ISSUE THREAD

**Issue by dtrippedaqlik** [balexbyrd/sense-FieldUI#6]
Hi bale, this is more of a request than an issue, which I was hoping I could bring to your attention. I'm a consultant with qlik and first off just wanted to say your extension has saved me countless times coming from the oldschool Qlikview dev perspective, when I am searching for an option to present menu items and drop downs with a single selected value. However there are 2 issues I increasingly encounter with clients that I was hoping some sort of fix/workaround could be developed outside of manipulations to the data model. When you have a dropdown list, it will always display the first value of the dimension shown, regardless of whether an item has been selected or not. To the clients/users this is extremely confusing as it implies to them that a selection has been made already, even if the field has not been highlighted, or a selection is showing up in the breadcrumb bar. To this point I've had to work around this by creating either a blank value, or "Please select one" value within the dimension, or else add a footnote to remind the user a value must be selected before it applies. The simplest solution would be to show the field name, or by default create a "please select one" type entry, in place of an unselected value, until the drop down list has been clicked and an item select.

In tangent to this issue, is that of default values. I get increasingly odd behavior with default values, unless they are specifically numerical. When trying to default on a text value for example, I find the following : 
1) only works with single word dimension values
2) that it will default to that value as expected, but then once I switch from that default, it will not allow me to properly switch back to that original selected value. The dropdown may allow me to select the default value again, but the engine treats it as if I was on the last value I had selected. i.e. I have values A,B,C,D and I default to A, and all tables/data load with A as selected. When I switch to let's say C , all tables/data switch appropriately, same for B and D. But if I then switch from C back to A, all data in charts/tables remains as if I still had C selected. 

This has lead me to recommend against starting with a default value unless the dropdown is numerical, which defeats the point of a single value selected listbox. I think if these 2 items were able to be addressed this extension would become standard in any Sense developers toolkit, as it replaces a great deal of functionality lost from our qlikview bag of tricks. Thanks for your consideration on this and if you need to reach out to me for any further info/feedback you can catch me at Damien.trippeda@qlik.com 

Thanks,
-D

**Comment by balexbyrd** [comment]
Hi D! Happy to hear you've had success with the extension. 

For the first issue, please see the most recent push. I seemed to have killed two birds with one stone on the dropdown (ability to select the first value in the field, and showing 'Nothing selected'). This should take care of your issue, I know it's not the field name but it should still suffice. If you need the field name to show, I'd suggest using the Title or Subtitle.

For the second, the default value function does give me and apparently others heart burn as well. I haven't come up with an elegant solution that fits all scenarios. I know Michael Clemens (js engineer @ Qlik ) is pretty talented and could probably help if you're in need. I'll keep this ticket open and see if I can find a fix when I have time. Thanks again! 

Alex
