### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by BenSPX** [balexbyrd/sense-FieldUI#7]
Hi! I created two Dropdown, Listbox style visuals on the same sheet. One works, and the other I can't make selections. The only thing different between them is the field. There is nothing unusual about the second field that I am aware of. Any thoughts?

**Comment by balexbyrd** [comment]
Hi Ben, I was not able to replicate your issue. I put two dropdowns on the same screen with two different field names and they worked just fine. I can't think of anything unusual -- hope this has worked itself out on your end!
